# Generated by Django 5.0.6 on 2024-05-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_board', '0002_category_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_change',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
