# Generated by Django 5.0.6 on 2024-05-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_board', '0004_alter_post_date_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_change',
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
